// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID
	Username    string
	Password    string
	Image       sql.NullString
	Email       string
	Createdat   time.Time
	Updatedat   time.Time
	Accesstoken uuid.UUID
}
