// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id,username,userId,contentText,contextImage,likes,createdAt,updatedAt)
VALUES ($1, $2, $3, $4, $5, $6, $7 ,$8)
RETURNING id, username, userid, contenttext, contextimage, likes, createdat, updatedat
`

type CreatePostParams struct {
	ID           uuid.UUID
	Username     string
	Userid       uuid.UUID
	Contenttext  string
	Contextimage sql.NullString
	Likes        int32
	Createdat    time.Time
	Updatedat    time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Username,
		arg.Userid,
		arg.Contenttext,
		arg.Contextimage,
		arg.Likes,
		arg.Createdat,
		arg.Updatedat,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Userid,
		&i.Contenttext,
		&i.Contextimage,
		&i.Likes,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1 AND userId = $2
`

type DeletePostParams struct {
	ID     uuid.UUID
	Userid uuid.UUID
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.Userid)
	return err
}

const likePost = `-- name: LikePost :exec
UPDATE posts
SET likes = likes + 1,
    updatedAt = $2
WHERE id = $1
`

type LikePostParams struct {
	ID        uuid.UUID
	Updatedat time.Time
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.ExecContext(ctx, likePost, arg.ID, arg.Updatedat)
	return err
}
